# Generated by Django 4.2.13 on 2024-11-10 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b4cklog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('backlog_completed', models.ManyToManyField(blank=True, related_name='backlog_completed', to='b4cklog.game')),
                ('backlog_completed_100', models.ManyToManyField(blank=True, related_name='backlog_completed_100', to='b4cklog.game')),
                ('backlog_played', models.ManyToManyField(blank=True, related_name='backlog_played', to='b4cklog.game')),
                ('backlog_playing', models.ManyToManyField(blank=True, related_name='backlog_playing', to='b4cklog.game')),
                ('backlog_want_to_play', models.ManyToManyField(blank=True, related_name='backlog_want_to_play', to='b4cklog.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
