# Generated by Django 4.2.4 on 2023-08-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4cklog', '0005_platform_abbreviation'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backlog_completed',
            field=models.ManyToManyField(blank=True, related_name='backlog_completed', to='b4cklog.game'),
        ),
        migrations.AddField(
            model_name='profile',
            name='backlog_completed_100',
            field=models.ManyToManyField(blank=True, related_name='backlog_completed_100', to='b4cklog.game'),
        ),
        migrations.AddField(
            model_name='profile',
            name='backlog_played',
            field=models.ManyToManyField(blank=True, related_name='backlog_played', to='b4cklog.game'),
        ),
        migrations.AddField(
            model_name='profile',
            name='backlog_playing',
            field=models.ManyToManyField(blank=True, related_name='backlog_playing', to='b4cklog.game'),
        ),
        migrations.AddField(
            model_name='profile',
            name='backlog_want_to_play',
            field=models.ManyToManyField(blank=True, related_name='backlog_want_to_play', to='b4cklog.game'),
        ),
    ]
