# Generated by Django 4.2.4 on 2023-08-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('cover', models.URLField(default='default.jpg')),
                ('first_release_date', models.DateField(null=True)),
            ],
        ),
    ]
