# Generated by Django 4.2.4 on 2023-08-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4cklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.URLField(default='https://images.app.goo.gl/6L3u5nmSG4Lt4ntf8'),
        ),
    ]
