# Generated by Django 4.2.4 on 2023-08-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b4cklog', '0002_alter_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.URLField(blank=True),
        ),
    ]
